# syntax=docker/dockerfile:1
FROM debian:bookworm

# unpriviledged user
USER root
RUN useradd -m devdocs

# seed
WORKDIR /home/devdocs/devdocs-airgap
ADD --chown=devdocs devdocs-airgap.tar.bz2 ./

# system packages
USER root
RUN ./dda.sh apt

# setup
USER devdocs
RUN ./dda.sh setup

# server-compatible locale
ENV LANG C.UTF-8

# start the server
EXPOSE 8080/tcp
CMD ["./dda.sh", "serve"]
